### ISSUE TITLE
Error when authenticating

### ISSUE THREAD

**Issue by zsleo** [geoffsmith82/GmailAuthSMTP#6]
I juts downloaded you GMailAuthDemo app and ran it in Delphi 10.4.1

I have a Gmail account and when I Authenticate I get the follwoing error at "GMailAuthDemo" of "TEnhancedOAuth2Authenticator.ChangeAuthCodeToAccesToken":

raised exception class EHTProtocolException with message 'HTTP:1.1 400 Bad Request'

This happens when I select the Gmail account in the browser session.

What am I doing wrong?

TIA

**Comment by joshlour** [comment]
I'm getting the same issue. Would love to know the answer. Hard to know if it's OAuth issue or a Delphi Issue.

**Comment by geoffsmith82** [comment]
Can you use fiddler to see what is actually requested?

https://www.telerik.com/fiddler

**Comment by joshlour** [comment]
This is the GET Request;
GET http://localhost:2132/?code=4/0AX4XfWiRPs-JUBlU4O_6VEdyEEFdFReLcemxC54zR2auA-1Rs85Fw5JA7C-rnsTVnH3yfQ&scope=openid%20https://mail.google.com/&authuser=0&prompt=consent

I did notice the above line of code with a localhost request rather than a url.

![Screenshot 2022-03-25 152128](https://user-images.githubusercontent.com/101678713/160053701-23978866-2223-47c6-b3f5-cf51ab267a19.png)

**Comment by joshlour** [comment]
The below are the LRequest URL from ChangeAuthCodeToAccesToken
Changed my ClientID to read CLIENT_ID
Changed my Secret to read CLIENT_SECRET


Google LRequest
http://localhost/?grant_type=authorization_code&code=4/0AX4XfWjXUowY_etL_X05rjXvjttCdspHuQsc3dIuZAbl13LsEwFMs-hHgBYQfTV4FLspEA&client_id=CLIENT_ID.apps.googleusercontent.com&client_secret=CLIENT_SECRET&redirect_uri=http://localhost:2132

Microsoft LRequest
http://localhost/?grant_type=authorization_code&code=0.AWcAEV6zIm3WUU6aC2Fb7p6XL-jJlBqdgDVGpDACuS6NhygAAAA.AQABAAIAAAD--DLA3VO7QrddgJg7WevraT5YK0pndSBjP1E-qKfPCNwjETTdPDu6IlzaiJw6lvlv3iJcKyJHknu3HIZqPKvLk3acupNVU5rjhuk7eI-P_P5XyKIS8sA-OSInBpziFX5yxf7Er5ai6J2JJt9RFIfO3pgSkNysNR5np17zHMjZroe9sLYlJOQzyS-VFdy7IRwhQlCsTRWHoz_5eR5LVa3yHtiXxnp8xtcxtXWglKifeocBdDzAGqI8w_oRrX2lrV39wwCH7Vrmu9wPwyePc4MboRMaUvX3-AiqoASfNQaHRA6fUQJiWbhjAjHSInY2onCBn3tukvD5UvhWq5isOV8GZyIxzEewSxZfbPOofZAZJmXqgEzxDYkdc-vQtLa6GMggkcc_tuAFc9hPisJQZWcNH7IXVhldkLJR1xVUhmvsIudt1_z2vy3NxeggC1PXXLG6kyDsXgAzu8hivMK3UcHsnzlZrBs7do_x0r4YlLKpjuJ6MQu2pAqqTz41DKlAwraiLsvG_d3It9Np_BKJ5iG9p4EHd3LzcpQLBLt2MhdxYC25YX-1KOeNDAABU8h3S5cNwkOUQHCkcM1_zfMMDNaMT6CA7plwdI6suzREe7cEYB3PTr_7SBEtZ9UUcr5oNB4NxD7CHDz_wsxk9YEyYogdXy3QZEPkY11Ao19sc9FLepmeNSBagH3joNOlyeilp7ldXbZ-IBMKfsmqdmj_3CgQnaOxeC1oUsgYPSSJV5o3bHLbT1NDKO7SkmtqrUZI14AgAA&client_id=CLIENT_ID&client_secret=&redirect_uri=http://localhost:2132

I also noticed that the Client Secret for Microsoft LRequest isn't populating even though it's filled in.

**Comment by geoffsmith82** [comment]
The client secret should not be required if it is setup as a public client.  I have been able to partially replicate the issue - I have pushed up a change that will hopefully fix it.... but I'm not sure if it was something else that changed as well.  So if you want to test the change have a look at the latest commit.

**Comment by joshlour** [comment]
Hi Geoff,
Thanks so much. That looks to have resolved the issue. I can now connect, read and transmit. I found it so hard to sift through the Microsoft documentation to find out how this was to be achieved. Really appreciate the example.
Best Regards,
Josh.
