### ISSUE TITLE
error sending email

### ISSUE THREAD

**Issue by megatkurniawan** [geoffsmith82/GmailAuthSMTP#7]
hello,

I have a problem sending an email, the error message is like this.
![image](https://user-images.githubusercontent.com/25611625/112233339-dc945f80-8c6c-11eb-8071-3ad4d35f65ad.png)

what causes this error message to appear?

**Comment by geoffsmith82** [comment]
Try changing  IdSSLIOHandlerSocketSMTP.SSLOptions.Method  to sslvTLSv1_2

I think that should fix the problem you are having.

**Comment by megatkurniawan** [comment]
it is working well now,
Thanks you
