### ISSUE TITLE
how do we know that the mail was sent?

### ISSUE THREAD

**Issue by giurfiufiufgiu** [geoffsmith82/GmailAuthSMTP#9]
Hey, 

This is a Great code. And I would like to thank you for supplying it. 

In the Form there is a Check if Send. Which works if you send the mail to yourself.
Is there a way to receive a more definitive answer if the mail was accepted? to inform the user?

like checking in outgoing mail box?
or receiving status from the server ?

Thanks.

**Comment by geoffsmith82** [comment]
Hi,
I added the "Check Msg's" button basically to make it the simpliest test of Authentication for POP3.  It also doesn't affect the mailbox in any way.  I have added a message box now to show that the message was sent.  If the message can't be accepted by the mail server, the code will raise an exception.  This only indicates that the message was accepted and not that it was delivered to the recepients inbox though.

**Comment by giurfiufiufgiu** [comment]
"Check Msg's" button checks the inbox. as we need to test the sent mail folder.

If I wont find a way to get the equivalent to http status 200 then the option of "no exception" will be it.

**Comment by geoffsmith82** [comment]
I've just added another button for authenticating with IMAP.  I haven't done the complete process, but you could select the "Sent Mail" mailbox and examine its contents.

**Comment by giurfiufiufgiu** [comment]
I go with no exception Then it was sent. Thanks
